### ISSUE TITLE
Add callback function handlers

### ISSUE THREAD

**Issue by ymarcon** [datashield/DSI#15]
On `datashield.aggregate` and `datashield.assign`, add callback functions to be called when request is successful or in error, for each study node. This does not affect DSI specific implementations.

```
results <- datashield.aggregate(conns, 
                      expr = quote(someFunction(D, 123)), 
                      success = function(study, result) {
                          // do something with study's result
                      },
                      error = function(study, message) {
                          // do something with study's error
                      })
```

**Comment by ymarcon** [comment]
@StuartWheater I have implemented this feature. You could give it a try and tell whether it is useful. See some usage examples in the functions' documentation.

**Comment by StuartWheater** [comment]
I have used the latest DSI (GitHub: "datashield/DSI", "master") to run the dsBaseClient v6.2 test suit, and I also did some tests which use "error" and "success" call-backs. All worked.

One thing to note, naturally, for datashield.assign's success call-back does not have a "result" argument.
