### ISSUE TITLE
datashield.aggregate error incorrectly reported in the case of a single opal object

### ISSUE THREAD

**Issue by IulianD** [datashield/DSI#5]
Hello,
Quick test case:
```
x <- opals[[1]] # x is an actual OpalConnection object, not a list
datashield.aggregate(x, quote(setDFdefinition(TRUE)),  async = FALSE) # some server function with an error in it...
Error in .appendError(n, e$message) : object 'n' not found
```
I see this at line 68 of datashield.aggregate:
```
   rval <- tryCatch({
      res <- dsAggregate(conns, expr)
      dsFetch(res)
    }, error = function(e) {
      .appendError(n, e$message)
      NULL
    })
```
(that is line 68 in the file here on github, including the doc lines)
I think n is out of scope here, 'conns' is itself the object, so the correct way is probably:
```
....
.appendError(conns@name, e$message)
...
```

Meant to say thanks for this software for a long time so... thanks :) it's great!

Cheers,
Iulian

**Comment by ymarcon** [comment]
Good catch. I think the error is at line [datashield.aggregate.R#L72](https://github.com/datashield/DSI/blob/master/R/datashield.aggregate.R#L72). Same issue at [datashield.assign.R#L136](https://github.com/datashield/DSI/blob/master/R/datashield.assign.R#L136) and other places (copy-paste is evil!).

**Comment by ymarcon** [comment]
Fixed, you can try with `devtools::install_github("datashield/DSI", ref = "master")`.
